-- Repair existing tables created before integer IDs were auto-generated.
-- Run this once in the Supabase SQL Editor for an existing deployment.

DO $$
DECLARE
  table_name TEXT;
  sequence_name TEXT;
  max_id BIGINT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['projects', 'life_updates', 'academics']
  LOOP
    IF EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND information_schema.columns.table_name = table_name
        AND column_name = 'id'
        AND is_identity = 'NO'
    ) THEN
      EXECUTE format(
        'ALTER TABLE public.%I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY',
        table_name
      );
    END IF;

    sequence_name := pg_get_serial_sequence(format('public.%I', table_name), 'id');
    EXECUTE format('SELECT MAX(id) FROM public.%I', table_name) INTO max_id;

    IF max_id IS NULL THEN
      PERFORM setval(sequence_name::regclass, 1, false);
    ELSE
      PERFORM setval(sequence_name::regclass, max_id, true);
    END IF;
  END LOOP;
END $$;
